# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47468f408a5210f47b7f25d11180d7fc62cc5e3dfbd5401c9bb4c4824202b9c8a60b0964dde867f10f96d377acbc3c9120342da9bbf48b82b700837dde01af7

test:
  secret_key_base: 96e6e4277d3eac2d7abb25ec009e0563002656f471962cb277bbe88eea0480928fb30695cb7aaf6d19695c41b3926c4388a2bd7a551f23e050f396d88bf404b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
development:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
